// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // For migrations, prefer non-pooling connection, then try other options
    url: process.env["POSTGRES_URL_NON_POOLING"] || 
        process.env["DATABASE_URL"] || 
        process.env["POSTGRES_PRISMA_URL"] || 
        process.env["POSTGRES_URL"],
  },
});
